### ISSUE TITLE
Error on sendMessage() in 1.0.0

### ISSUE THREAD

**Issue by FlorianANAYA** [jdachtera/node-rtpmidi#20]
Hello,

There seems to be a bug in 1.0.0. On every call of the function sendMessage(), the following error occurs:
`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at Session.sendMessage (/home/webmidi/node_modules/rtpmidi/src/Session.js:220:18)
    at Socket.<anonymous> (/home/webmidi/rtpMIDIWEBServer/Main.js:78:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /home/webmidi/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

Here is the code condensed (Everything is not called immediately, and the ready event is fired before sendMessage() is called) : 
`console.log("Creating rtpMIDI session");`
`rtpSession = rtpmidi.manager.createSession({"localName": "rtpMIDIWEBServer", "address": "127.0.0.1", "bonjourName": "rtpMIDIWEBServer", "port": 5004});`
`rtpSession.on('ready', function()`
`{`
`    console.log("rtpMIDI session ready");`
`});`
`...Later in code...`
`var ar = [0xb0, fader.m_MIDINote, fader.m_value];`
`console.log(ar);`
`rtpSession.sendMessage(ar);`

The ouput in the console is the following
`Creating rtpMIDI session`
`rtpMIDI session ready`
`MidiNote=0, Value=24`
`[ 176, 0, 24 ]`
`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at Session.sendMessage (/home/webmidi/node_modules/rtpmidi/src/Session.js:220:18)
    at Socket.<anonymous> (/home/webmidi/rtpMIDIWEBServer/Main.js:78:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /home/webmidi/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

And the process exits.

The problems disappear when I rollback to 0.1.9 with npm. Am I missing something ? Or is there a change in 1.0.0 that isn't documented ?

Thank you

**Comment by sq4** [comment]
Hi , Still the same problem with 1.0.0 ? 
The  session.sendMessage function is changed. 
in 0.1.9 there was just  argument necessary. 
In the 1.0.0 version the arguments are sendMessage(comexTime, command, ...args).
    session.sendMessage([0x90, 0x01, 0x7f]);
becomes:
    session.sendMessage(0, [0x90, 0x01, 0x7f]);
in the Session.js check this function, i've added some slight modifications and now it's working. 

`
Session.prototype.sendMessage = function sendMessage(comexTime, command, ...args) {
	let cTime = comexTime;
	let cmd;
	
	if (arguments.length === 1) {
		cTime = this.now();
		[cmd] = args; // Picks first arg using array destructing
	} else {
		cTime = comexTime - this.startTime;
	}
	if (!Buffer.isBuffer(command)) {
		cmd = Buffer.from(command);
	}

	this.queue.push({ comexTime: this.now(), data: cmd });
	this.queueFlush();
};`

Keep in mind, you have to wait for the status message otherwise it's not working. 
Kind Regards

**Comment by FlorianANAYA** [comment]
Hello,

Thanks for the explaination, I will update my code.
 Also thanks for the update, the old code now works with the new version too.

**Comment by soccermitchy** [comment]
Is the fixed version published on npm? Using the latest version that is there, I still get this error.

**Comment by soccermitchy** [comment]
Actually, even the version from this repo (installed via `npm install git+https://github.com/jdachtera/node-rtpmidi.git`) gives the same exception
